index:
    path: /
    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\UtilisateurController::login
    methods: [POST]
listUtilisateurs:
    path: /utilisateur
    controller: App\Controller\UtilisateurController::list
    methods: [GET]

listClient:
    path: /client
    controller: App\Controller\ClientController::list
    methods: [GET]
addClient:
    path: /client
    controller: App\Controller\ClientController::add
    methods: [POST]

listNotefrais:
    path: /utilisateur/{id}/notefrais
    controller: App\Controller\NotefraisController::list
    methods: [GET]
listNotefraisByDate:
    path: /utilisateur/{id}/notefrais/tri/date
    controller: App\Controller\NotefraisController::listByDate
    methods: [GET]
listNotefraisByClient:
    path: /utilisateur/{id}/notefrais/tri/client
    controller: App\Controller\NotefraisController::listByClient
    methods: [GET]
addNotefrais:
    path: /utilisateur/{id}/notefrais
    controller: App\Controller\NotefraisController::add
    methods: [POST]

listAllDepense:
    path: /utilisateur/{idU}/depense
    controller: App\Controller\DepenseController::listAll
    methods: [GET]
listDepense:
    path: /notefrais/{idN}/depense
    controller: App\Controller\DepenseController::list
    methods: [GET]
addDepense:
    path: /notefrais/{idN}/depense
    controller: App\Controller\DepenseController::add
    methods: [POST]
catchFrais:
    path: /depense/{idD}/frais
    controller: App\Controller\DepenseController::catchFrais
    methods: [GET]
catchTrajet:
    path: /depense/{idD}/trajet
    controller: App\Controller\DepenseController::catchTrajet
    methods: [GET]

catchJustificatif:
    path: /notefrais/{idN}/depense/{idD}/justificatif
    controller: App\Controller\JustificatifController::catch
    methods: [GET]
addJustificatif:
    path: /notefrais/{idN}/depense/{idD}/justificatif
    controller: App\Controller\JustificatifController::add
    methods: [POST]